androidURL=http://127.0.0.1:4723
androidAutomationName=UiAutomator2
androidAppLocation=apps/Android.SauceLabs.Mobile.Sample.app.2.7.1.apk

/////////////////////////////////////////////////////////////////////////////////

iosAutomationName=XCUITest
iosBundleId=com.saucelabs.SwagLabsMobileApp
iosAppLocation=apps/iOS.Simulator.SauceLabs.Mobile.Sample.app.2.7.1.app
